# The Site Configuration
# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: Europe/Amsterdam

# jekyll-seo-tag settings
title: Stefan Stranger's Blog

tagline: AI, Azure, PowerShell and DevOps

description: >-
  This is my personal blog. I work at Microsoft as a Consultant.
  You can find some of my open source projects on Github.
  I like to share my knowledge about AI, Azure, PowerShell and DevOps

url: "https://stefanstranger.github.io"

github:
  username: stefanstranger

twitter:
  username: sstranger

social:
  name: Stefan Stranger
  email: stefan@stranger.nl
  links:
    - https://twitter.com/sstranger
    - https://github.com/stefanstranger
    - https://www.linkedin.com/in/stefanstranger

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID

# Prefer color scheme setting (empty = follow system + toggle)
theme_mode:

# the avatar on sidebar, support local or CORS resources
avatar: https://github.com/stefanstranger.png

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  provider: giscus
  giscus:
    repo: "stefanstranger/stefanstranger.github.io"
    repo_id: "MDEwOlJlcG9zaXRvcnkxNTEyMjg0MjE="
    category: "Announcements"
    category_id: "DIC_kwDOCQOQBc4C384E"
    mapping: "pathname"
    strict: "0"
    input_position: "bottom"
    lang: "en"
    reactions_enabled: "1"

assets:
  self_host:
    enabled: false

pwa:
  enabled: true
  cache:
    enabled: true

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /:year/:month/:day/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

plugins:
  - jemoji
  - jekyll-archives

include:
  - .well-known

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/